### PR TITLE
Guard against multiple buildscript blocks in a single script

### PR DESCRIPTION
**Pull request by cbeams**
See failing test case. Part of #72.

### CODE REVIEW

**Comment by bamboo** [comment]
This doesn't seem to match the behaviour of the Groovy frontend which is to consider all `buildscript` blocks in the first step.

**Comment by cbeams** [comment]
I just did a very quick test on the Groovy side, and I thought it was discarding all but the first `buildscript { }`. If that's not the case, then we should adjust this, including the test case.

**Comment by bamboo** [comment]
Check this one out, it will only compile if you uncomment the `dependencies` block and at least one of the `repositories` blocks:
 
```
buildscript {
    //repositories { mavenCentral() }
}

buildscript {
    //repositories { jcenter() }
}

buildscript {
    //dependencies { classpath("junit:junit:4.12") }
}

org.junit.Assert.assertTrue(true)

task dumpRepositories {
    doLast {
        buildscript.repositories.each {
            println(it.url)
        }
    }
}
```

**Comment by oehme** [comment]
I think only allowing one `buildscript` block at the very top of the build file is a good idea. It's a very slight departure from Groovy, but if we were to redesign it, that's what we would do. We have done the same for the `plugins` block already.

**Comment by bamboo** [comment]
Resolved in 588ab800a0aae6c379e258938ef28af605295fb7.

**Pull request closed without merging**
